repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.64.0
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
        args:
          - tfvars hcl --output-file terraform.tfvars.model .
      # - id: terraform_tflint
      #   args: ['--args=--config=__GIT_WORKING_DIR__/.tflint.hcl']
      # - id: terraform_tfsec
      - id: terraform_validate
