repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.88.2
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
        args:
          - --args=--hide providers
      - id: terraform_tfsec
        args:
          - --args=--exclude-downloaded-modules
          - --args=-e azure-keyvault-content-type-for-secret,azure-keyvault-ensure-secret-expiry
      # - id: terraform_validate
      #   args:
      #     - --init-args=-lockfile=readonly
      #     - --args=-json
      #     - --args=-no-color
      #     - --hook-config=--retry-once-with-cleanup=true
