resource_group_name  = "terraform-state-rg"
storage_account_name = "tfinfprodio"
container_name       = "terraform-state"
# key                  = "io-infra.core-prod.tfstate"
key = "io-infra.core-prod-step3.tfstate"
