affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: elastic
          operator: In
          values:
            - eck
admissionWebhooks:
  certManager:
    enabled: false