pr:
  autoCancel: false
  branches:
    include:
      - main
  paths:
    include:
      - "src/domains/sign-app"
      - "src/domains/sign"
      - ".devops/sign-code-review-pipelines.yml"
    exclude:
      - '**/*.lock.hcl'

# parameters:
#   - name: "COMMON"
#     displayName: "code-review COMMON folder@PROD subscription "
#     type: boolean
#     default: True
#     values:
#       - False
#       - True
#   - name: "APP_BETA"
#     displayName: "code-review APP folder@AKS BETA"
#     type: boolean
#     default: True
#     values:
#       - False
#       - True
#   - name: "APP_PROD01"
#     displayName: "code-review APP folder@AKS PROD01"
#     type: boolean
#     default: True
#     values:
#       - False
#       - True

variables:
  TIME_OUT: 10

pool:
  vmImage: "ubuntu-20.04"

resources:
  repositories:
    - repository: terraform
      type: github
      name: pagopa/azure-pipeline-templates
      ref: refs/tags/v2.4.0
      endpoint: "io-azure-devops-github-ro"

stages:
  #
  # Common
  #
  - stage: tf_plan_common_on_prod
    dependsOn: []
    pool:
      name: io-prod-linux
    jobs:
      - job: tf_plan_common_on_prod
        strategy:
          parallel: 1
        timeoutInMinutes: $[variables.TIME_OUT]
        steps:
          - checkout: self
          # 1. Install terraform
          - template: templates/terraform-setup/template.yaml@terraform
          # 2. Run terraform plan sign
          - template: templates/terraform-plan/template.yaml@terraform
            parameters:
              ENVIRONMENT: "prod"
              WORKINGDIR: "src/domains/sign"
              AZURE_SERVICE_CONNECTION_NAME: PROD-IO-SERVICE-CONN
