# only manual
trigger: none
pr: none

variables:
  TIME_OUT: 10

pool:
  vmImage: "ubuntu-20.04"

resources:
  repositories:
    - repository: terraform
      type: github
      name: pagopa/azure-pipeline-templates
      ref: refs/tags/v2.4.0
      endpoint: "io-azure-devops-github-ro"

stages:
  #
  # Common
  #
  - stage: tf_apply_common_on_prod
    dependsOn: []
    pool:
      name: io-prod-linux
    jobs:
      - job: tf_apply_common_on_prod
        strategy:
          parallel: 1
        timeoutInMinutes: $[variables.TIME_OUT]
        steps:
          - checkout: self
          # 1. Install terraform
          - template: templates/terraform-setup/template.yaml@terraform
          # 2. Run terraform plan sign
          - template: templates/terraform-plan/template.yaml@terraform
            parameters:
              AZURE_SERVICE_CONNECTION_NAME: PROD-IO-SERVICE-CONN
              ENVIRONMENT: "prod"
              WORKINGDIR: "src/domains/sign"
          # 3. Run terraform apply
          - template: templates/terraform-apply/template.yaml@terraform
            parameters:
              AZURE_SERVICE_CONNECTION_NAME: PROD-IO-SERVICE-CONN
              ENVIRONMENT: prod
              WORKINGDIR: "src/domains/sign"
