name: Run APIM Backup

on: 
  workflow_dispatch:
    inputs:
      environment:
        type: string
        required: true
      storage_account_name:
        type: string
        required: true
      storage_account_resource_group:
        type: string
        required: true
      storage_account_container:
        type: string
        required: true
      apim_name:
        type: string
        required: true
      apim_resource_group:
        type: string
        required: true
      backup_name:
        type: string
        required: true
      env_vars:
        type: string
        required: false
        description: List of environment variables to set up, given in env=value format.

env:
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

jobs:
  backup:
    name: 'Backup APIM'
    runs-on: ubuntu-20.04
    environment: ${{ inputs.environment }}-ci
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        name: Checkout

      - name: Set Environment Variables
        if: ${{ inputs.env_vars }}
        run: |
          for i in "${{ inputs.env_vars }}"
          do
            printf "%s\n" $i >> $GITHUB_ENV
          done

      - name: Azure Login
        uses: azure/login@6b2456866fc08b011acb422a92a4aa20e2c4de32 # v2.1.0
        with:
          client-id: ${{ env.ARM_CLIENT_ID }}
          tenant-id: ${{ env.ARM_TENANT_ID }}
          subscription-id: ${{ env.ARM_SUBSCRIPTION_ID }}

      # https://github.com/Azure/cli/releases
      - name: Azure CLI
        uses: azure/cli@4db43908b9df2e7ac93c8275a8f9a448c59338dd # v1
        with:
          inlineScript: |
            set -e
            key=$(az storage account keys list \
            -g ${{ env.STORAGE_ACCOUNT_RG }} \
            -n ${{ env.STORAGE_ACCOUNT_NAME }} \
            --query [0].value -o tsv)

            az apim backup \
            --name ${{ env.APIM_NAME }} \
            -g ${{ env.APIM_RG }} \
            --backup-name ${{ env.BACKUP_NAME }} \
            --storage-account-name ${{ env.STORAGE_ACCOUNT_NAME }} \
            --storage-account-container ${{ env.STORAGE_ACCOUNT_CONTAINER }} \
            --storage-account-key $key
        env:
          APIM_NAME: ${{ inputs.apim_name }}
          APIM_RG: ${{ inputs.apim_resource_group }}
          BACKUP_NAME: ${{ inputs.backup_name }}
          STORAGE_ACCOUNT_CONTAINER: ${{ inputs.storage_account_container }}
          STORAGE_ACCOUNT_RG: ${{ inputs.storage_account_resource_group }}
          STORAGE_ACCOUNT_NAME: ${{ inputs.storage_account_name }}