name: Continuous Delivery on bonus

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "src/domains/bonus/**"

jobs:
  release_prod:
    uses: pagopa/dx/.github/workflows/infra_apply.yaml@check-modules-lock-in-cicd
    name: Terraform Apply
    secrets: inherit
    with:
      environment: prod
      base_path: "src/domains/bonus"
      use_private_agent: false
