name: Continuous Integration on prod cgn

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
      - ready_for_review
    paths:
      - "src/domains/cgn**"
      - ".github/workflows/cgn_**"

permissions:
  id-token: write
  contents: read

env:
  DIR: "src/domains/cgn"
  AZURE_ENVIRONMENT: prod

jobs:
  code_review_prod:
    uses: ./.github/workflows/call_code_review.yml
    name: Terraform Plan
    secrets: inherit
    with:
      environment: prod
      dir: ${{ env.DIR }}
