name: Release - Dev Common TF Apply

# This pipeline starts automatically when a PR is merged into 'main'.
#
# It is responsible for managing changes related to "common" infrastructure,
#
# This pipeline first executes a plan and then an apply, which must be approved by the team.

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "src/common/dev/**"
      - "src/common/_modules/**"
      - ".github/workflows/common_dev_deploy.yaml"
jobs:
  dev_itn_common_deploy:
    uses: pagopa/dx/.github/workflows/infra_apply.yaml@main
    name: Dev - Code Deploy
    secrets: inherit
    with:
      environment: dev
      base_path: src/common
      use_private_agent: true
