name: PR - Core TF Apply

# This pipeline start automatically when a PR will be merged in 'main'
#
# is responsible for managing changes relating to the NEW infrastructure only, 
# so it checks whether the change has occurred only in the folders inside "paths"
#
## NOTE: 'NEW infrastructure' mean the new terraform infrastructure inside the src/core/prod folder, which no longer requires the terraform.sh script to be applied.
#
# This pipeline first executes a plan and then an apply, which must be approved by the team.

on: 
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "src/core/prod/**"
      - "src/core/_modules/**"
      - ".github/workflows/core_deploy.yaml"
jobs:
  prod_itn_core_deploy:
    uses: pagopa/dx/.github/workflows/infra_apply.yaml@main
    name: Prod - Code Deploy
    secrets: inherit
    with:
      environment: prod
      base_path: src/core
