name: PR - Core TF Validation

# This pipeline start automatically when a PR is opened
#
# is responsible for managing changes relating to the NEW infrastructure only, 
# so it checks whether the change has occurred only in the folders inside "paths"
#
## NOTE: 'NEW infrastructure' mean the new terraform infrastructure inside the src/core/prod folder, which no longer requires the terraform.sh script to be applied.

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
      - ready_for_review
    paths:
      - "src/core/prod/**"
      - "src/core/_modules/**"
      - ".github/workflows/core_code_review.yaml"

jobs:
  prod_itn_core_code_review:
    uses: pagopa/dx/.github/workflows/infra_plan.yaml@main
    name: Prod - Code Review
    secrets: inherit
    with:
      environment: prod
      base_path: src/core
