name: Release - Core TF Apply

# This pipeline starts automatically when a PR is merged into 'main'.
#
# It is responsible for managing changes related to "core" infrastructure,
#
# This pipeline first executes a plan and then an apply, which must be approved by the team.

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "src/core/prod/**"
      - "src/core/_modules/**"
      - ".github/workflows/core_deploy.yaml"
jobs:
  prod_itn_core_deploy:
    uses: pagopa/dx/.github/workflows/infra_apply.yaml@check-modules-lock-in-cicd
    name: Prod - Code Deploy
    secrets: inherit
    with:
      environment: prod
      base_path: src/core
      use_private_agent: true
