name: PR - Core TF Validation

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
      - ready_for_review
    paths:
      - "src/core/prod/**"
      - "src/core/_modules/**"
      - ".github/workflows/core_code_review.yaml"

jobs:
  prod_itn_core_code_review:
    uses: pagopa/dx/.github/workflows/infra_plan.yaml@main
    name: Prod - Code Review
    secrets: inherit
    with:
      environment: prod
      base_path: src/core
