name: PR - Core TF Validation

# This pipeline starts automatically when a PR is opened.
#
# It is responsible for managing changes related to "core" infrastructure,

on:
  merge_group:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
      - ready_for_review
    paths:
      - "src/core/prod/**"
      - "src/core/_modules/**"
      - ".github/workflows/core_code_review.yaml"

jobs:
  prod_itn_core_code_review:
    uses: pagopa/dx/.github/workflows/infra_plan.yaml@fix-infra-plan-group
    name: Prod - Code Review
    secrets: inherit
    with:
      environment: prod
      base_path: src/core
      use_private_agent: true
