name: PR - Core TF Apply

on: 
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "src/core/prod/**"
      - "src/core/_modules/**"
      - ".github/workflows/core_deploy.yaml"
jobs:
  prod_itn_core_deploy:
    uses: pagopa/dx/.github/workflows/infra_apply.yaml@main
    name: Prod - Code Deploy
    secrets: inherit
    with:
      environment: prod
      base_path: src/core
