name: Continuous Delivery on cosmos-api

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "src/cosmos-api/**"

jobs:
  release_prod:
    uses: ./.github/workflows/call_release.yaml
    name: Deploy Infrastructure
    secrets: inherit
    with:
      environment: prod
      dir: "src/cosmos-api/prod"
