name: Continuous Delivery on elt

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "src/domains/elt/**"

jobs:
  release_prod:
    uses: pagopa/dx/.github/workflows/infra_apply.yaml@main
    name: Terraform Apply
    secrets: inherit
    with:
      environment: prod
      base_path: "src/domains/elt"
      use_private_agent: true
