name: Continuous Integration on elt

on:
  merge_group:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
      - ready_for_review
    paths:
      - "src/domains/elt/**"
      - ".github/workflows/elt_**"
      - "src/_modules/test_users/**"

jobs:
  code_review_prod:
    uses: pagopa/dx/.github/workflows/infra_plan.yaml@main
    name: Terraform Plan
    secrets: inherit
    with:
      environment: prod
      base_path: "src/domains/elt"
      use_private_agent: true
