name: Continuous Integration on elt

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
      - ready_for_review
    paths:
      - "src/domains/elt**"
      - ".github/workflows/elt_**"

jobs:
  code_review_prod:
    uses: pagopa/dx/.github/workflows/infra_plan.yaml@main
    name: Terraform Plan
    secrets: inherit
    with:
      environment: prod
      dir: "src/domains/elt/prod"
      use_private_agent: true
