name: Continuous Integration on functions itn

on:
  merge_group:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
      - ready_for_review
    paths:
      - "src/domains/functions-itn/**"
      - ".github/workflows/functions_itn_**"

jobs:
  code_review_prod:
    uses: pagopa/dx/.github/workflows/infra_plan.yaml@main
    name: Terraform Plan
    secrets: inherit
    with:
      environment: prod
      base_path: "src/domains/functions-itn"
      use_private_agent: true