name: GitHub Runner Job AutoScaler

on:
  workflow_dispatch:
  schedule:
    - cron: '0 09 * * MON-FRI'
    - cron: '0 18 * * MON-FRI'

env:
  resource-group: 'dev-andreag' #'io-p-github-runner-rg'
  job-name: 'github-actions-runner-job'

jobs:
  turn_on:
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        id: login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: 'a4e96bcd-59dc-4d66-b2f7-5547ad157c12' # ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Increase minimum replicas
        if: github.event.schedule == '0 09 * * *'
        run: |
          az containerapp job update \
            --resource-group ${{ env.resource-group }} \
            --name ${{ env.job-name }} \
            --min-executions 1

      - name: Decrease minimum replicas
        if: github.event.schedule == '0 18 * * *'
        run: |
          az containerapp job update \
            --resource-group ${{ env.resource-group }} \
            --name ${{ env.job-name }} \
            --min-executions 0
