name: Continuous Integration on prod ioweb

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
      - ready_for_review
    paths:
      - "src/domains/ioweb**"
      - ".github/workflows/ioweb_prod**"

permissions:
  id-token: write
  contents: read

env:
  DIR: "src/domains/ioweb"
  AZURE_ENVIRONMENT: prod

jobs:

  terraform_plan_job:
    name: Terraform Plan
    runs-on: self-hosted
    environment: prod-ci
    steps:
      - name: Checkout
        id: checkout
        # from https://github.com/actions/checkout/commits/main
        uses: actions/checkout@1f9a0c22da41e6ebfa534300ef656657ea2c6707
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Setup terraform
        id: setup-version
        # https://github.com/pagopa/terraform-install-action/commits/main
        uses: pagopa/terraform-install-action@1f76f593176e58c423b88d72273a612ba7ba430b

      - name: Terraform plan common
        # from https://github.com/pagopa/terraform-plan-azure-action/commits/main
        uses: pagopa/terraform-plan-azure-action@392aca28cbb33f5dc28215dfb72385e136fd813b
        with:
          client_id: ${{ secrets.AZURE_CLIENT_ID_CI }}
          tenant_id: ${{ secrets.AZURE_TENANT_ID }}
          subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          dir: ${{ env.DIR }}-common
          azure_environment: prod

      - name: Terraform plan app (weu-prod01)
        # from https://github.com/pagopa/terraform-plan-azure-action/commits/main
        uses: pagopa/terraform-plan-azure-action@392aca28cbb33f5dc28215dfb72385e136fd813b
        with:
          client_id: ${{ secrets.AZURE_CLIENT_ID_CI }}
          tenant_id: ${{ secrets.AZURE_TENANT_ID }}
          subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          dir: ${{ env.DIR }}-app
          azure_environment: weu-prod01
