name: Continuous Delivery on load-test

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "src/load-test/**"

jobs:
  code_review_prod:
    uses: pagopa/dx/.github/workflows/infra_apply.yaml@check-modules-lock-in-cicd
    name: Release Infrastructure
    secrets: inherit
    with:
      environment: prod
      base_path: src/load-test
