name: Continuous Integration on load-test

on:
  merge_group:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
      - ready_for_review
    paths:
      - "src/load-test/**"
      - ".github/workflows/load_test_**.yaml"

jobs:
  code_review_prod:
    uses: pagopa/dx/.github/workflows/infra_plan.yaml@check-modules-lock-in-cicd
    name: Core Review Infrastructure Plan
    secrets: inherit
    with:
      environment: prod
      base_path: src/load-test
