name: Continuous Delivery on load-test

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "src/load-test/**"

jobs:
  code_review_prod:
    uses: pagopa/dx/.github/workflows/infra_apply.yaml@8ec64257f46bb8c03509d317b42fbf6a2da2c63a # main
    name: Release Infrastructure
    secrets: inherit
    with:
      environment: prod
      base_path: src/load-test
