name: Continuous Integration on notification hubs

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
      - ready_for_review
    paths:
      - "src/notification-hubs/**"
      - ".github/workflows/notification-hubs_**.yaml"

jobs:
  code_review_prod:
    uses: pagopa/dx/.github/workflows/infra_plan.yaml@main
    name: Core Review Infrastructure Plan
    secrets: inherit
    with:
      environment: prod
      base_path: src/notification-hubs
