name: Continuous Delivery on notification hubs

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "src/notification-hubs/**"

jobs:
  code_review_prod:
    uses: pagopa/dx/.github/workflows/infra_apply.yaml@main
    name: Release Infrastructure
    secrets: inherit
    with:
      environment: prod
      base_path: src/notification-hubs
