name: Release - Platform TF Apply

# This pipeline starts automatically when a PR is merged into 'main'.
#
# It is responsible for managing changes related to the "Platform" infrastructure.
#
# This pipeline first executes a plan and then an apply, which must be approved by the team.

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "src/platform/**"
      - ".github/workflows/platform_dev_deploy.yaml"
jobs:
  platform_cdn_dev_deploy:
    uses: pagopa/dx/.github/workflows/infra_apply.yaml@main
    name: Dev - Code Deploy
    secrets: inherit
    with:
      environment: dev
      base_path: src/platform
      use_private_agent: true
