name: Release - Platform PROD CDN TF Apply

# This pipeline starts automatically when a PR is merged into 'main'.
#
# It is responsible for managing changes related to the "Platform - PROD - CDN" infrastructure.
#
# This pipeline first executes a plan and then an apply, which must be approved by the team.

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "src/platform/cdn/prod/**"
      - "src/platform/cdn/_modules/**"
      - ".github/workflows/platform_cdn_deploy.yaml"
jobs:
  platform_cdn_prod_deploy:
    uses: pagopa/dx/.github/workflows/infra_apply.yaml@main
    name: Prod - Code Deploy
    secrets: inherit
    with:
      environment: prod
      base_path: src/platform/cdn
      use_private_agent: true
