name: PR - Platform DEV TF Validation

# This pipeline starts automatically when a PR is opened.
#
# It is responsible for managing changes related to the "Platform" infrastructure.

on:
  merge_group:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
      - ready_for_review
    paths:
      - "src/platform/**"
      - ".github/workflows/platform_dev_code_review.yaml"

jobs:
  platform_cdn_dev_code_review:
    uses: pagopa/dx/.github/workflows/infra_plan.yaml@main
    name: Dev - Code Review
    secrets: inherit
    with:
      environment: dev
      base_path: src/platform
      use_private_agent: true
