name: PR - Labeler

on:
  workflow_dispatch:
  merge_group:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

permissions:
  contents: read
  pull-requests: write

jobs:
  labeler:
    name: PR Labeler
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9 # v5.0.0
        with:
          sync-labels: true
